# Generated by Django 3.2.3 on 2021-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210601_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='add_datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='add_datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.IntegerField(choices=[(0, 'Poszukiwany / Poszukiwana'), (1, 'Znaleziony / Znaleziona')], default=1),
        ),
    ]
